//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCO.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        public string nroCita { get; set; }
        public Nullable<int> idPaciente { get; set; }
        public int nroIdentificProf { get; set; }
        public string idEspecialidad { get; set; }
        public Nullable<System.DateTime> fechaCita { get; set; }
        public Nullable<System.DateTime> horaCita { get; set; }
        public string observacion { get; set; }
        public System.DateTime fechaRegCita { get; set; }
        public Nullable<System.DateTime> fechaModCita { get; set; }
        public string idConsultorio { get; set; }
    
        public virtual GCO_Consultorio GCO_Consultorio { get; set; }
        public virtual GCO_Especialidad GCO_Especialidad { get; set; }
        public virtual Paciente Paciente { get; set; }
        public virtual Profesional Profesional { get; set; }
    }
}
