//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCO.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class GCO_Orden_De_Pago
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GCO_Orden_De_Pago()
        {
            this.GCO_Orden_De_Atencion = new HashSet<GCO_Orden_De_Atencion>();
        }
    
        public string nroOrdenPago { get; set; }
        public Nullable<decimal> precioTotOP { get; set; }
        public Nullable<decimal> descuentoOP { get; set; }
        public Nullable<System.DateTime> fechaRegOP { get; set; }
        public Nullable<System.DateTime> fechaModOP { get; set; }
        public string idEstado { get; set; }
    
        public virtual GCO_Estado GCO_Estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GCO_Orden_De_Atencion> GCO_Orden_De_Atencion { get; set; }
    }
}
