//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCO.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class GCO_Solicitud_De_Insumos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GCO_Solicitud_De_Insumos()
        {
            this.GCO_Solicitud_De_Insumos_Detalle = new HashSet<GCO_Solicitud_De_Insumos_Detalle>();
        }
    
        public System.Guid idSolicitudInsumos { get; set; }
        public Nullable<System.Guid> idEstado { get; set; }
        public string observacionSI { get; set; }
        public Nullable<System.DateTime> fechaRegSI { get; set; }
        public Nullable<int> nroIdentificProf { get; set; }
    
        public virtual GCO_Estado GCO_Estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GCO_Solicitud_De_Insumos_Detalle> GCO_Solicitud_De_Insumos_Detalle { get; set; }
        public virtual Profesional Profesional { get; set; }
    }
}
