//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCO.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class GCO_Solicitud_De_Insumos_Detalle
    {
        public string idSolInsumDet { get; set; }
        public string idSolicitudInsumos { get; set; }
        public int codArticulo { get; set; }
        public Nullable<int> cantidadInsumo { get; set; }
        public Nullable<System.DateTime> fechaRegSID { get; set; }
    
        public virtual Articulo Articulo { get; set; }
        public virtual GCO_Solicitud_De_Insumos GCO_Solicitud_De_Insumos { get; set; }
    }
}
