//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCO.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class GCO_Articulo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GCO_Articulo()
        {
            this.GCO_Solicitud_De_Insumos_Detalle = new HashSet<GCO_Solicitud_De_Insumos_Detalle>();
        }
    
        public System.Guid idArticulo { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string unidadMedida { get; set; }
        public string TipoArticulo { get; set; }
        public Nullable<decimal> costosxUM { get; set; }
        public Nullable<System.DateTime> fechaRegArticulo { get; set; }
        public Nullable<System.DateTime> fechaModArticulo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GCO_Solicitud_De_Insumos_Detalle> GCO_Solicitud_De_Insumos_Detalle { get; set; }
    }
}
