//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCO.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class GCO_Orden_De_Pago_Detalle
    {
        public System.Guid idOrdenDePagoDetalle { get; set; }
        public Nullable<System.Guid> idOrdenDePago { get; set; }
        public Nullable<System.Guid> idPlanTratamientoDetalle { get; set; }
        public Nullable<System.Guid> idEstado { get; set; }
        public Nullable<System.DateTime> fechaRegOA { get; set; }
        public Nullable<System.DateTime> fechaModOA { get; set; }
        public Nullable<decimal> PrecioCobrado { get; set; }
    
        public virtual GCO_Estado GCO_Estado { get; set; }
        public virtual GCO_Orden_De_Pago GCO_Orden_De_Pago { get; set; }
        public virtual GCO_Plan_De_Tratamiento_Detalle GCO_Plan_De_Tratamiento_Detalle { get; set; }
    }
}
