//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCO.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class GCO_Tipo_Atencion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GCO_Tipo_Atencion()
        {
            this.GCO_Orden_De_Atencion = new HashSet<GCO_Orden_De_Atencion>();
        }
    
        public string idTipoAtencion { get; set; }
        public string descTipoAtencion { get; set; }
        public string estadoTipoAtencion { get; set; }
        public Nullable<System.DateTime> fechaRegTA { get; set; }
        public Nullable<System.DateTime> fechaModTA { get; set; }
        public Nullable<decimal> precioTipoAtencion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GCO_Orden_De_Atencion> GCO_Orden_De_Atencion { get; set; }
    }
}
