//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCO.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class GCO_Orden_De_Atencion
    {
        public string idOrdenAtencion { get; set; }
        public string idPlanTratamiento { get; set; }
        public string idTipoAtencion { get; set; }
        public string idEstado { get; set; }
        public Nullable<System.DateTime> fechaRegOA { get; set; }
        public Nullable<System.DateTime> fechaModOA { get; set; }
        public string nroOrdenPago { get; set; }
        public string numOrdenAtencion { get; set; }
    
        public virtual GCO_Estado GCO_Estado { get; set; }
        public virtual GCO_Tipo_Atencion GCO_Tipo_Atencion { get; set; }
        public virtual GCO_Orden_De_Pago GCO_Orden_De_Pago { get; set; }
        public virtual GCO_Plan_De_Tratamiento GCO_Plan_De_Tratamiento { get; set; }
    }
}
