//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCO.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class GCO_Ficha_Dental
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GCO_Ficha_Dental()
        {
            this.GCO_Plan_De_Tratamiento = new HashSet<GCO_Plan_De_Tratamiento>();
        }
    
        public System.Guid idFichaDental { get; set; }
        public Nullable<System.Guid> idHistoriaClinica { get; set; }
        public string diagnosticoFD { get; set; }
        public string observacionFD { get; set; }
        public string notaAvanceFD { get; set; }
        public Nullable<System.DateTime> fechaRegFD { get; set; }
        public Nullable<System.DateTime> fechaModFD { get; set; }
        public Nullable<System.Guid> idEstado { get; set; }
    
        public virtual GCO_Estado GCO_Estado { get; set; }
        public virtual GCO_HistoriaClinica GCO_HistoriaClinica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GCO_Plan_De_Tratamiento> GCO_Plan_De_Tratamiento { get; set; }
    }
}
