//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCO.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class GCO_Paciente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GCO_Paciente()
        {
            this.GCO_Cita = new HashSet<GCO_Cita>();
            this.GCO_HistoriaClinica = new HashSet<GCO_HistoriaClinica>();
        }
    
        public System.Guid idPaciente { get; set; }
        public string TipoDocIdentidad { get; set; }
        public string NumDocIdentidad { get; set; }
        public string nombresPaciente { get; set; }
        public string apePatPaciente { get; set; }
        public string apeMatPaciente { get; set; }
        public Nullable<System.DateTime> fechaNacPaciente { get; set; }
        public string PaisNacPaciente { get; set; }
        public string sexo { get; set; }
        public string telefono { get; set; }
        public string direccion { get; set; }
        public string distrito { get; set; }
        public string provincia { get; set; }
        public string departamento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GCO_Cita> GCO_Cita { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GCO_HistoriaClinica> GCO_HistoriaClinica { get; set; }
    }
}
