//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCO.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class GCO_Cita
    {
        public System.Guid idCita { get; set; }
        public Nullable<System.Guid> idPaciente { get; set; }
        public Nullable<int> nroIdentificProf { get; set; }
        public Nullable<System.Guid> idEspecialidad { get; set; }
        public Nullable<System.DateTime> fechaCita { get; set; }
        public string observacion { get; set; }
        public Nullable<System.DateTime> fechaRegCita { get; set; }
        public Nullable<System.DateTime> fechaModCita { get; set; }
        public Nullable<System.Guid> idConsultorio { get; set; }
    
        public virtual GCO_Consultorio GCO_Consultorio { get; set; }
        public virtual GCO_Especialidad GCO_Especialidad { get; set; }
        public virtual GCO_Paciente GCO_Paciente { get; set; }
        public virtual Profesional Profesional { get; set; }
    }
}
