//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCO.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoriaClinica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HistoriaClinica()
        {
            this.GCO_Ficha_Dental = new HashSet<GCO_Ficha_Dental>();
        }
    
        public int nroHistoria { get; set; }
        public Nullable<int> idPaciente { get; set; }
        public string grupoSanguineo { get; set; }
        public string observacion { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<System.DateTime> fechaActualizacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GCO_Ficha_Dental> GCO_Ficha_Dental { get; set; }
        public virtual Paciente Paciente { get; set; }
    }
}
